name: subsonic-arubislander # you probably want to 'snapcraft register <name>'
version: '6.1.3+snap1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Your complete, personal media streamer. # 79 char long summary
description: |
  Stream from your own computer.
  Your media — your terms.
  Enjoy your music and movies everywhere.
  Share with family and friends.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  lib-path:
    command: echo "$LD_LIBRARY_PATH"
  lame:
    command: lame
  ffmpeg:
    command: ffmpeg

  subsonic:
#    command: subsonic.sh
    command: wrapper.sh
    daemon: forking
    restart-condition: on-abnormal
    plugs: 
      - home
      - network
      - network-bind
      - removable-media
parts:
  subsonic:
    # See 'snapcraft plugins'
    plugin: dump  
    source: https://s3-eu-west-1.amazonaws.com/subsonic-public/download/subsonic-6.1.3-standalone.tar.gz

  jdk:
    plugin: nil
    stage-packages: 
      - openjdk-8-jre-headless
      - lame
      #- ffmpeg
    prepare: |
      rm $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-8-openjdk-*/jre/lib/security/cacerts
      #echo "** Deleting $PWD\cacerts"
      #rm cacerts
      #ln -s ../../../../../../../etc/ssl/certs/java/cacerts cacerts
    after: [ffmpeg]

  launcher:
    plugin: dump
    source: bin
