name: subsonic-arubislander # you probably want to 'snapcraft register <name>'
version: '6.1.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Your complete, personal media streamer. # 79 char long summary
description: |
  Stream from your own computer.
  Your media — your terms.
  Enjoy your music and movies everywhere.
  Share with family and friends.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  subsonic:
    command: wrapper.sh
    daemon: forking
    restart-condition: on-abnormal
    plugs: 
      - network
      - network-bind
      - removable-media

parts:
  subsonic:
    # See 'snapcraft plugins'
    plugin: dump  
    source: https://s3-eu-west-1.amazonaws.com/subsonic-public/download/subsonic-6.1.1-standalone.tar.gz
  
  jdk:
    plugin: nil
    stage-packages: 
      - openjdk-8-jre-headless
      - lame
      - ffmpeg
  
  launcher:
    plugin: dump
    source: bin